services:
    # retrieve all registered posts.
    Goulmima\BlogBundle\Utils\Aggregation\Aggregator:
        arguments: ['@doctrine.orm.default_entity_manager']
    Goulmima\BlogBundle\Utils\Aggregation\AggregatorInterface: '@Goulmima\BlogBundle\Utils\Aggregation\Aggregator'
